"""
Mock LLM Provider for local development without GPU.

Returns realistic template responses for each agent type,
enabling full UI/UX development and testing locally.
"""

from __future__ import annotations

import asyncio
import json
import random
import time
from typing import AsyncIterator, Optional

from app.models.provider import ModelProvider, GenerationConfig, GenerationResult
from app.utils.logger import setup_logger

logger = setup_logger("mock_provider")

# Pre-built mock responses for different agent contexts
MOCK_RESPONSES = {
    "technical_question": [
        "Can you explain the difference between a stack and a queue? When would you use each data structure in a real-world application?",
        "How would you design a rate limiter for an API? Walk me through your approach including the data structures you'd use.",
        "Explain the concept of database indexing. What are B-trees and how do they improve query performance?",
        "What is the difference between SQL and NoSQL databases? When would you choose one over the other?",
        "Describe the event loop in Node.js. How does it handle asynchronous operations?",
    ],
    "behavioral_question": [
        "Tell me about a time when you had to work with a difficult team member. How did you handle the situation?",
        "Describe a project where you had to learn a new technology quickly. What was your approach?",
        "Give me an example of a time when you failed. What did you learn from the experience?",
        "How do you prioritize tasks when you have multiple deadlines approaching simultaneously?",
        "Tell me about a time when you took initiative to improve a process or system.",
    ],
    "coding_question": [
        "Write a function that finds the longest palindromic substring in a given string. Optimize for time complexity.",
        "Implement a LRU (Least Recently Used) cache with O(1) get and put operations.",
        "Write a function to detect if a linked list has a cycle. Can you do it with O(1) space?",
    ],
    "evaluation": json.dumps({
        "technical_accuracy": 7.5,
        "depth_of_understanding": 7.0,
        "communication_clarity": 8.0,
        "problem_solving": 7.5,
        "code_quality": 0,
        "composite_score": 7.5,
        "reasoning": "The candidate demonstrated solid understanding of core concepts with clear communication. Could improve on edge case analysis.",
        "key_strengths": ["Clear explanation", "Good use of examples", "Structured approach"],
        "areas_to_improve": ["Edge case handling", "Time complexity analysis", "System design depth"]
    }),
    "resume_analysis": json.dumps({
        "candidate_name": "Sample Candidate",
        "skills": ["Python", "JavaScript", "React", "Node.js", "SQL", "Docker"],
        "experience": [{"title": "Software Engineer", "company": "Tech Corp", "duration": "2 years"}],
        "education": [{"degree": "B.Tech Computer Science", "institution": "IIT Delhi"}],
        "strengths": ["Strong programming fundamentals", "Full-stack experience", "Cloud deployment knowledge"],
        "gaps": ["Limited system design experience", "No ML/AI exposure", "Missing leadership experience"],
        "summary": "A mid-level full-stack developer with strong fundamentals and practical project experience."
    }),
    "feedback_report": json.dumps({
        "overall_score": 72,
        "technical_score": 75,
        "behavioral_score": 70,
        "coding_score": 68,
        "hiring_recommendation": "hire",
        "strengths": ["Strong coding fundamentals", "Good communication skills", "Quick learner"],
        "weaknesses": ["System design needs improvement", "Limited production experience"],
        "improvement_roadmap": {
            "short_term": ["Practice system design problems", "Build a production-grade side project"],
            "long_term": ["Gain distributed systems experience", "Contribute to open source"]
        },
        "summary": "Solid candidate with good fundamentals. Recommended for hire with mentorship support."
    }),
    "default": "This is a mock response for local development. In the GPU environment, this would be generated by the LLM. The response demonstrates the expected format and structure that the real model would produce.",
}


class MockProvider(ModelProvider):
    """
    Mock LLM provider for local development.
    
    Simulates LLM responses with realistic delays and
    pre-built templates. No GPU required.
    """

    def __init__(self, simulate_delay: bool = True, delay_range: tuple = (0.3, 1.0)):
        self.simulate_delay = simulate_delay
        self.delay_range = delay_range
        self.call_count = 0
        logger.info("MockProvider initialized (local dev mode)")

    async def _simulate_delay(self):
        if self.simulate_delay:
            delay = random.uniform(*self.delay_range)
            await asyncio.sleep(delay)

    def _get_mock_response(self, prompt: str, system_prompt: str = "") -> str:
        prompt_lower = prompt.lower()
        sys_lower = system_prompt.lower()
        combined = f"{sys_lower} {prompt_lower}"

        if "evaluat" in combined or "score" in combined or " assess" in combined:
            return MOCK_RESPONSES["evaluation"]
        if "resume" in combined or "parse" in combined or "extract" in combined or "profile" in combined:
            return MOCK_RESPONSES["resume_analysis"]
        if "feedback" in combined or "report" in combined or "recommendation" in combined:
            return MOCK_RESPONSES["feedback_report"]
        if "code" in combined or "implement" in combined or "algorithm" in combined:
            return random.choice(MOCK_RESPONSES["coding_question"])
        if "behavioral" in combined or "leadership" in combined or "conflict" in combined:
            return random.choice(MOCK_RESPONSES["behavioral_question"])
        if "technical" in combined or "system design" in combined or "database" in combined:
            return random.choice(MOCK_RESPONSES["technical_question"])
        return MOCK_RESPONSES["default"]

    async def generate(
        self,
        prompt: str,
        system_prompt: str = "",
        config: Optional[GenerationConfig] = None,
    ) -> GenerationResult:
        self.call_count += 1
        start = time.time()
        await self._simulate_delay()
        text = self._get_mock_response(prompt, system_prompt)
        elapsed = (time.time() - start) * 1000

        return GenerationResult(
            text=text,
            model="mock-provider-v1",
            tokens_used=len(text) // 4,
            prompt_tokens=len(prompt) // 4,
            completion_tokens=len(text) // 4,
            latency_ms=elapsed,
            finish_reason="stop",
        )

    async def generate_stream(
        self,
        prompt: str,
        system_prompt: str = "",
        config: Optional[GenerationConfig] = None,
    ) -> AsyncIterator[str]:
        self.call_count += 1
        text = self._get_mock_response(prompt, system_prompt)
        words = text.split()
        for word in words:
            if self.simulate_delay:
                await asyncio.sleep(random.uniform(0.02, 0.08))
            yield word + " "

    async def generate_structured(
        self,
        prompt: str,
        system_prompt: str = "",
        output_schema: Optional[dict] = None,
        config: Optional[GenerationConfig] = None,
    ) -> dict:
        result = await self.generate(prompt, system_prompt, config)
        try:
            return json.loads(result.text)
        except json.JSONDecodeError:
            return {"response": result.text}

    def get_model_info(self) -> dict:
        return {
            "provider": "mock",
            "model": "mock-provider-v1",
            "environment": "local",
            "gpu_required": False,
            "total_calls": self.call_count,
        }

    async def health_check(self) -> bool:
        return True
